server:
  port: 8903

logging:
  level:
    root: info

spring:
  application:
    name: feign-server
  profiles:
    active: ribbon

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      HELLOWORLD-CLIENT:
        connectTimeout: 5000
        readTimeout: 30000