server:
  port: 8763

spring:
  application:
    name: helloworld-client
  profiles:
    active: @profiles.active@

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
