server:
  port: 8905

spring:
  application:
    name: zipkin-server
  zipkin:
    enabled: false #关闭本工程的推送到zipkin服务的功能

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
