server:
  port: 8902

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/WorkSpace/GhostCloud/config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
