server:
  port: 8901

logging:
  level:
    root: debug

spring:
  application:
    name: ribbon-server
  profiles:
    active: @profiles.active@
  zipkin:
    enabled: true
    base-url: http://ZIPKIN-SERVER
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
