server:
  port: 8901

logging:
  level:
    root: debug

spring:
  application:
    name: ribbon-server
  profiles:
    active: @profiles.active@

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
